import { LaptopBridge, type DeviceCredentials, type Manifest, type SecureDeviceStore } from './laptop-bridge.js';

declare global { interface Window { orbitySecureStore?: SecureDeviceStore } }
const app = document.querySelector<HTMLDivElement>('#app') ?? (() => { throw new Error('Mobile root is missing'); })();
class UnavailableSecureStore implements SecureDeviceStore { async load(): Promise<DeviceCredentials | null> { throw new Error('This companion needs the native secure-storage adapter before it can pair.'); } async save(): Promise<void> { throw new Error('This companion needs the native secure-storage adapter before it can pair.'); } async clear(): Promise<void> { throw new Error('This companion needs the native secure-storage adapter before it can unpair.'); } }
const bridge = new LaptopBridge(window.orbitySecureStore || new UnavailableSecureStore()); let manifest: Manifest | null = null; let activeProfileId = '';
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char));
function icon(kind: 'plus'|'mic'|'voice'|'settings'|'scan') { const paths={plus:'<path d="M12 5v14M5 12h14"/>',mic:'<rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0M12 18v3M8.5 21h7"/>',voice:'<path d="M7 8v8M12 5v14M17 8v8"/>',settings:'<path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="3"/>',scan:'<path d="M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[kind]}</svg>`; }
function renderPairing(message=''){app.innerHTML=`<section class="remote-shell pairing-shell"><header><span class="orb">O</span><button class="icon-control" aria-label="Connection settings">${icon('settings')}</button></header><div class="pairing-copy"><div class="orb-wave" aria-hidden="true"><i></i><i></i><i></i></div><h1>Pair with your laptop</h1><p>Scan the QR code displayed in OrbityLabs, or enter its eight-character pairing code.</p>${message?`<p class="notice">${escapeHtml(message)}</p>`:''}</div><form id="manual-pair" class="pair-form"><label>Laptop address<input name="host" inputmode="url" autocomplete="url" placeholder="http://192.168.1.8:8787" required /></label><label>Pairing code<input name="code" autocomplete="one-time-code" autocapitalize="characters" placeholder="ABCD1234" required /></label><button class="primary" type="submit">Connect to laptop</button></form><button class="scan-action" id="scan">${icon('scan')} Scan QR code</button></section>`;document.querySelector<HTMLFormElement>('#manual-pair')?.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.currentTarget as HTMLFormElement);try{manifest=await bridge.pairFromCode(String(data.get('host')),String(data.get('code')),'OrbityLabs Mobile');activeProfileId=manifest.profiles[0]?.id||'';renderChat();}catch(error){renderPairing(error instanceof Error?error.message:'Pairing failed.');}});document.querySelector<HTMLButtonElement>('#scan')?.addEventListener('click',()=>renderPairing('QR scanning is provided by the installed mobile shell. Use the code option until the scanner adapter is configured.'));}
function renderChat(message=''){const profiles=manifest?.profiles||[];const active=profiles.find(profile=>profile.id===activeProfileId)||profiles[0];if(!active)return renderPairing('Your laptop has no profiles yet. Create one on the laptop, then reconnect.');activeProfileId=active.id;app.innerHTML=`<section class="remote-shell chat-shell"><header class="chat-header"><div><span class="presence"></span><strong>${escapeHtml(active.name)}</strong><small>CEO remote</small></div><button class="icon-control" id="profile-picker" aria-label="Choose profile">${icon('settings')}</button></header><div class="message-space"><div class="ceo-orb"><span>CEO</span></div><h1>How can I help?</h1><p>Your message is sent to the CEO running on your laptop.</p>${message?`<div class="remote-message">${escapeHtml(message)}</div>`:''}</div><form id="composer" class="composer"><button type="button" class="composer-icon" aria-label="Add context">${icon('plus')}</button><input name="message" placeholder="Message CEO" autocomplete="off" required /><button type="button" class="composer-icon" aria-label="Voice input">${icon('mic')}</button><button type="submit" class="voice-send" aria-label="Send message">${icon('voice')}</button></form></section>`;document.querySelector<HTMLButtonElement>('#profile-picker')?.addEventListener('click',renderProfilePicker);document.querySelector<HTMLFormElement>('#composer')?.addEventListener('submit',async event=>{event.preventDefault();const input=new FormData(event.currentTarget as HTMLFormElement).get('message');if(typeof input!=='string'||!input.trim())return;try{await bridge.messageCEO(active.id,input.trim());renderChat('Sent to your laptop CEO. The laptop accepted the request.');}catch(error){renderChat(error instanceof Error?error.message:'Message could not be sent.');}});}
function renderProfilePicker(){const profiles=manifest?.profiles||[];app.innerHTML=`<section class="remote-shell profile-shell"><header><button class="back" id="back">Back</button><strong>Choose profile</strong><span></span></header><div class="profile-list">${profiles.map(profile=>`<button class="profile-row ${profile.id===activeProfileId?'selected':''}" data-profile="${escapeHtml(profile.id)}"><span>${escapeHtml(profile.name.slice(0,1).toUpperCase())}</span><div><strong>${escapeHtml(profile.name)}</strong><small>${escapeHtml(profile.kind||'Profile')}</small></div></button>`).join('')}</div></section>`;document.querySelector<HTMLButtonElement>('#back')?.addEventListener('click',()=>renderChat());document.querySelectorAll<HTMLButtonElement>('[data-profile]').forEach(button=>button.addEventListener('click',()=>{activeProfileId=button.dataset.profile||activeProfileId;renderChat();}));}
async function start(){try{manifest=await bridge.manifest();activeProfileId=manifest.profiles[0]?.id||'';renderChat();}catch{renderPairing();}}void start();
